api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

newsletter:
    type: rest
    resource: Core\ApiBundle\Controller\NewsletterController

logmessage:
    type: rest
    resource: Core\ApiBundle\Controller\LogMessageController