app_log_header:
    resource: "@AppBundle/Controller/LogHeaderController.php"
    type:     annotation

app_newsletter:
    resource: "@AppBundle/Controller/NewsletterController.php"
    type:     annotation

api:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"